#!/bin/bash

script_dir=$(dirname "${BASH_SOURCE[0]}")
cd "${script_dir}/.."

# push test-amd64 and test-arm64 images.
bazel run //:push_to_dockerhub_amd64
bazel run //:push_to_dockerhub_arm64

# Create the multiarch manifest.
docker manifest rm buchgr/bazel-remote-cache:latest
docker manifest create buchgr/bazel-remote-cache:latest \
    --amend buchgr/bazel-remote-cache:tmp-amd64 \
    --amend buchgr/bazel-remote-cache:tmp-arm64

# Push the multiarch manifest
docker manifest push buchgr/bazel-remote-cache:latest

echo "Go ahead and delete the tmp-amd64 and tmp-arm64 images from the web ui"
